<?php
/**
 * File to store fixed paths generated by defined GET-Params and Page-IDs
 *
 * @author Björn Schmitt
 *
 * Examples:
 *
 * ?tx_myextension_myplugin[controller]=Index&tx_myextension_myplugin[action]=show&tx_myextension_myplugin[item]=3
 *
 * 1. Params to paths
 *
 *  '[PAGE-ID]' => array(
 *    'tx_myextension_myplugin[controller]',
 *    'tx_myextension_myplugin[action]',
 *    'tx_myextension_myplugin[item]'
 *  )
 *
 *  Will convert to: [Page-Path]/Index/show/3/
 *
 * 2. Hide
 *
 *  '[PAGE-ID]' => array(
 *    'tx_myextension_myplugin[action]',
 *    'tx_myextension_myplugin[item]'
 *    array(
 * 	    'param' => 'tx_myextension_myplugin[controller]',
 *      'hide' => true
 *    )
 *  )
 *
 *  Will convert to: [Page-Path]/show/3/
 *
 * 3. Fixed mapping
 *
 *  '[PAGE-ID]' => array(
 *    'tx_myextension_myplugin[controller]',
 *    'tx_myextension_myplugin[action]',
 *    array(
 * 	    'param' => 'tx_myextension_myplugin[item]',
 *      'map' => array(
 *        '3' => 'custom-text'
 *      )
 *    )
 *  )
 *
 *  Will convert to: [Page-Path]/Index/show/custom-text/
 *
 * 4. Dynamic mapping
 *
 *  '[PAGE-ID]' => array(
 *    'tx_myextension_myplugin[controller]',
 *    'tx_myextension_myplugin[action]',
 *    array(
 * 	    'param' => 'tx_myextension_myplugin[item]',
 *      'sql'   => array(
 		  'field' => 'title' ,
 		  'from'  => 'tx_myextension_domain_model_post' ,
 		  'where' => 'uid = %s and deleted = 0'
 		)
 *    )
 *  )
 *
 *  Will convert to: [Page-Path]/Index/show/hello-world/
 *
 */

return array(
	// config here
);